### ISSUE TITLE
Test actions don't wait when run manually

### ISSUE THREAD

**Issue by progapandist** [lewagon/wait-on-check-action#13]
Ping @matiasalbarello :) 

Currently, [this line](https://github.com/lewagon/wait-on-check-action/blob/8261ca4a3d0175489f9d95c613a097757158ff91/.github/workflows/simple_task.yml#L15) doesn't seem to do anything (see https://github.com/lewagon/wait-on-check-action/runs/1725958933?check_suite_focus=true)

What if we make the `simple_check` action take some considerable time anyway? (and rename it accordingly, like "run for 3 minutes"). This will give us enough time to dispatch "test" actions and see if they work. I love the trigger scripts approach, but IMO testing in GHA's UX is easier and will be the way to go.

WDYT?

**Comment by matiasalbarello** [comment]
I'll take a look. I didn't check the manual triggering

**Comment by progapandist** [comment]
Basically all we need is a longer running job that one can manually trigger and then manually trigger jobs that depend on it
