### ISSUE TITLE
 Windows support

### ISSUE THREAD

**Issue by konserw** [lewagon/wait-on-check-action#27]
Hi!
I've got windows-based workflow and would like to use this action, but it appears to be linux-only, i.e. Github tells me:
```
Run lewagon/wait-on-check-action@v0.2
Error: Container action is only supported on Linux
```
Could you please add windows support?

**Comment by progapandist** [comment]
Hi! I would welcome the PR doing that, but so far none of our builds use Linux and I currently have no free time to dig into that. All contributions are welcome though!

**Comment by matiasalbarello** [comment]
Hi @konserw. The release v1.1.0 gives support to Windows and MacOS self-hosted runners. Enjoy!
