### ISSUE TITLE
Is this action support wait for workflow in a different repo?

### ISSUE THREAD

**Issue by nitzan-upstream** [lewagon/wait-on-check-action#3]
Hello,

Let's say I have workflow-A in repo-A which trigger with repository dispatch Workflow-B in repo-B and we want to wait in Workflow-A for Workflow-B to finish, is this possible? If so can you please provide an example?

Thank you

**Comment by progapandist** [comment]
Hi! It's not possible in the current implementation as it always looks in the current repo, see here https://github.com/lewagon/wait-on-check-action/blob/b55701e44d3c36232ee23a65e4baf1b5b60791eb/entrypoint.rb#L6

If you want to try forking and passing more arguments to the action, including the repo name — you can try to test if that works, a PR would be welcome!

**Comment by brianjmurrell** [comment]
The current code for entrypoint.rb on master seems quite different than https://github.com/kelu27/wait-on-check-action/commit/c1f750667217f02a7099.

So is foreign repository support in current master?
