### ISSUE TITLE
Add a new parameter `ignore-check-names`

### ISSUE THREAD

**Issue by kevinawoo** [lewagon/wait-on-check-action#38]
Currently, we can wait for all the jobs to finish, or we can wait for 1. When https://github.com/lewagon/wait-on-check-action/issues/35 is implemented that would allow us to wait for N number of checks.

It would be awesome if we could also "wait for everything except for X check(s)" as well. This way we'd can always wait for jobs to complete except for jobs we we'd want to ignore.

**Comment by matiasalbarello** [comment]
Hi @kevinawoo.
It's an interesting feature. We'll have it in mind.
Thanks!
