### ISSUE TITLE
The action only waits for 30 checks

### ISSUE THREAD

**Issue by ditman** [lewagon/wait-on-check-action#40]
We've noticed that in some cases the `wait-on-check` action is not waiting for all our checks ([here](https://github.com/flutter/flutter/issues/88120)).

It seems that some of the method calls in the Checks API might have a `per_page` parameter that is not being passed and defaults to 30? [Docs](https://docs.github.com/en/rest/reference/checks#list-check-runs-in-a-check-suite)), so if one has more than 30 checks, the action won't wait for all of them (we currently have 40).

Passing 100 to `per_page` might work on our repo, but for anybody with more than 100 checks, this action should probably handle pagination in the API (also, just to be on the safe side if the max of 100 changes to a lower value).

**Comment by ditman** [comment]
(I'm going to try and send a PR increasing the `per_page` limit to 100 in the relevant API call :) )

**Comment by ditman** [comment]
After looking at the code: `client.check_runs_for_ref` [here](https://github.com/lewagon/wait-on-check-action/blob/3ac63078fe8644f15c807e6419c8a8a1ec7913f1/app/services/github_checks_verifier.rb#L24) looks a lot like this API: [List check runs for a Git reference](https://docs.github.com/en/rest/reference/checks#list-check-runs-for-a-git-reference).

**Comment by matiasalbarello** [comment]
Now, with the next version release, the action will be capable of waiting up to 100 jobs. Thanks @ditman!

**Comment by ditman** [comment]
Thanks @matiasalbarello! We'll update to the latest hash/release ASAP!
