### ISSUE TITLE
Add support for macOS machines

### ISSUE THREAD

**Issue by efraespada** [lewagon/wait-on-check-action#47]
When defining:

```yaml
runs-on: macos-latest
```

Produces:
```
Run lewagon/wait-on-check-action@v1.0.0
Error: Container action is only supported on Linux
```

**Comment by matiasalbarello** [comment]
Hi @efraespada. I'm actually working on it. I'll be releasing a new version soon (this weekend)

**Comment by matiasalbarello** [comment]
Fixed here: https://github.com/lewagon/wait-on-check-action/pull/48

**Comment by efraespada** [comment]
Thanks @matiasalbarello 😄

**Comment by matiasalbarello** [comment]
Sorry, I had to roll back the last release. Will deploy it again soon.

**Comment by matiasalbarello** [comment]
Hi @efraespada. There's a pre-release version that you could try: v1.1.1. Please let me know if you find any problems. I'll be testing it for some time and probably will finally be the latest stable version.

**Comment by efraespada** [comment]
I'll check it ASAP. Thanks for your work ;)
