### ISSUE TITLE
This check is only supported in Linux not macos

### ISSUE THREAD

**Issue by yeshwant-hotstar** [lewagon/wait-on-check-action#57]
Run lewagon/wait-on-check-action@v1.0.0
  with:
    ref: refs/heads/main
    check-name: CI test
    repo-token: ***
    wait-interval: 10
    allowed-conclusions: success,skipped,cancelled
    verbose: true
Error: Container action is only supported on Linux

**Comment by matiasalbarello** [comment]
Hi @yeshwant-hotstar. Actually the version that introduces compatibility with MacOS is the latest [v1.1.1](https://github.com/lewagon/wait-on-check-action/releases/tag/v1.1.1)

**Comment by matiasalbarello** [comment]
If you find any issue, be aware of this other one: https://github.com/lewagon/wait-on-check-action/issues/52

**Comment by matiasalbarello** [comment]
Please let me know if the inquiry/issue was resolved. If not, feel free to re-open it.
