### ISSUE TITLE
Missing External Checks Statuses 

### ISSUE THREAD

**Issue by omkarkhatavkar** [lewagon/wait-on-check-action#78]
I have a case, where we run the test externally and updated it on the GitHub PR Checks. This GitHub action is unable to find that Check in the list of checks running or in other states. @matiasalbarello Do you know any workaround for this? 

Check Name is : Robottelo-Runner

e.g. 
https://github.com/omkarkhatavkar/robottelo/pull/50
https://github.com/omkarkhatavkar/robottelo/actions/runs/3854084036/jobs/6567696665

I need a similar approach shown below. to cross-check that all checks are passing on iterating over them  

```
> gh pr checks https://github.com/omkarkhatavkar/robottelo/pull/50
Some checks were not successful
2 failing, 3 successful, 1 skipped, and 0 pending checks

X  Automerge auto-cherry-picked pr  1m13s  https://github.com/omkarkhatavkar/robottelo/actions/runs/3854084036/jobs/6567696665
X  Robottelo-Runner
✓  Code Quality (3.8)               9m12s  https://github.com/omkarkhatavkar/robottelo/actions/runs/3849330929/jobs/6558199235
✓  Code Quality (3.9)               9m6s   https://github.com/omkarkhatavkar/robottelo/actions/runs/3849330929/jobs/6558199363
✓  Enforcing cherrypick labels      2s     https://github.com/omkarkhatavkar/robottelo/actions/runs/3854084009/jobs/6567696500
-  Add author to assignee                  https://github.com/omkarkhatavkar/robottelo/actions/runs/3849330909/jobs/6558199492
```

**Comment by michelau** [comment]
Just use a different action.  This one works for me for waiting on a Jenkins build to finish: https://github.com/marketplace/actions/wait-on-check

**Comment by omkarkhatavkar** [comment]
No need for this.
