### ISSUE TITLE
Can't find `action.yml`

### ISSUE THREAD

**Issue by CWSites** [lewagon/wait-on-check-action#84]
This has been working without an issue until today I got the following error which failed my build. I haven't changed any of my configuration settings, however I noticed that your action was updated within the last week?

![Screenshot 2023-02-22 at 3 09 27 PM](https://user-images.githubusercontent.com/1242102/220747746-2b8c4171-9ed7-4611-abeb-e9a741337814.png)

![Screenshot 2023-02-22 at 3 07 32 PM](https://user-images.githubusercontent.com/1242102/220747953-fc8d2921-4718-40ac-a3de-9af46d1832fd.png)

**Comment by ssaunier** [comment]
I'm using `lewagon/wait-on-check-action@v1.3.1` without any issue on my side, could you share the whole YAML of your action failing? Could you try locking `lewagon/wait-on-check-action` to `v1.3.1` in it and retry?

**Comment by CWSites** [comment]
I'll give it a shot, I locked it to `v1.2.0` and now it passes without any issues.
